In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/glove-global-vectors-for-word-representation/glove.6B.200d.txt
/kaggle/input/glove-global-vectors-for-word-representation/glove.6B.50d.txt
/kaggle/input/glove-global-vectors-for-word-representation/glove.6B.100d.txt


In [2]:
with open('/kaggle/input/glove-global-vectors-for-word-representation/glove.6B.50d.txt') as f:
    embeddings = f.read()

In [4]:
embeddings[:500]

'the 0.418 0.24968 -0.41242 0.1217 0.34527 -0.044457 -0.49688 -0.17862 -0.00066023 -0.6566 0.27843 -0.14767 -0.55677 0.14658 -0.0095095 0.011658 0.10204 -0.12792 -0.8443 -0.12181 -0.016801 -0.33279 -0.1552 -0.23131 -0.19181 -1.8823 -0.76746 0.099051 -0.42125 -0.19526 4.0071 -0.18594 -0.52287 -0.31681 0.00059213 0.0074449 0.17778 -0.15897 0.012041 -0.054223 -0.29871 -0.15749 -0.34758 -0.045637 -0.44251 0.18785 0.0027849 -0.18411 -0.11514 -0.78581\n, 0.013441 0.23682 -0.16899 0.40951 0.63812 0.47709'

In [37]:
embeddings_list = embeddings.split('\n')
embeddings_list[:3]

['the 0.418 0.24968 -0.41242 0.1217 0.34527 -0.044457 -0.49688 -0.17862 -0.00066023 -0.6566 0.27843 -0.14767 -0.55677 0.14658 -0.0095095 0.011658 0.10204 -0.12792 -0.8443 -0.12181 -0.016801 -0.33279 -0.1552 -0.23131 -0.19181 -1.8823 -0.76746 0.099051 -0.42125 -0.19526 4.0071 -0.18594 -0.52287 -0.31681 0.00059213 0.0074449 0.17778 -0.15897 0.012041 -0.054223 -0.29871 -0.15749 -0.34758 -0.045637 -0.44251 0.18785 0.0027849 -0.18411 -0.11514 -0.78581',
 ', 0.013441 0.23682 -0.16899 0.40951 0.63812 0.47709 -0.42852 -0.55641 -0.364 -0.23938 0.13001 -0.063734 -0.39575 -0.48162 0.23291 0.090201 -0.13324 0.078639 -0.41634 -0.15428 0.10068 0.48891 0.31226 -0.1252 -0.037512 -1.5179 0.12612 -0.02442 -0.042961 -0.28351 3.5416 -0.11956 -0.014533 -0.1499 0.21864 -0.33412 -0.13872 0.31806 0.70358 0.44858 -0.080262 0.63003 0.32111 -0.46765 0.22786 0.36034 -0.37818 -0.56657 0.044691 0.30392',
 '. 0.15164 0.30177 -0.16763 0.17684 0.31719 0.33973 -0.43478 -0.31086 -0.44999 -0.29486 0.16608 0.11963 -0.4132

In [36]:
data = {}


for emb in embeddings_list[:-1]:
    word = emb.split()[0]
    vec = emb.split()[1:]
    data[word] = np.array(vec, dtype='float')

In [38]:
# data

In [39]:
len(data)

400000

In [40]:
type(data)

dict

In [41]:
data['apple']

array([ 0.52042 , -0.8314  ,  0.49961 ,  1.2893  ,  0.1151  ,  0.057521,
       -1.3753  , -0.97313 ,  0.18346 ,  0.47672 , -0.15112 ,  0.35532 ,
        0.25912 , -0.77857 ,  0.52181 ,  0.47695 , -1.4251  ,  0.858   ,
        0.59821 , -1.0903  ,  0.33574 , -0.60891 ,  0.41742 ,  0.21569 ,
       -0.07417 , -0.5822  , -0.4502  ,  0.17253 ,  0.16448 , -0.38413 ,
        2.3283  , -0.66682 , -0.58181 ,  0.74389 ,  0.095015, -0.47865 ,
       -0.84591 ,  0.38704 ,  0.23693 , -1.5523  ,  0.64802 , -0.16521 ,
       -1.4719  , -0.16224 ,  0.79857 ,  0.97391 ,  0.40027 , -0.21912 ,
       -0.30938 ,  0.26581 ])

In [42]:
data['apple'].shape

(50,)

In [43]:
data['banana']

array([-0.25522 , -0.75249 , -0.86655 ,  1.1197  ,  0.12887 ,  1.0121  ,
       -0.57249 , -0.36224 ,  0.44341 , -0.12211 ,  0.073524,  0.21387 ,
        0.96744 , -0.068611,  0.51452 , -0.053425, -0.21966 ,  0.23012 ,
        1.043   , -0.77016 , -0.16753 , -1.0952  ,  0.24837 ,  0.20019 ,
       -0.40866 , -0.48037 ,  0.10674 ,  0.5316  ,  1.111   , -0.19322 ,
        1.4768  , -0.51783 , -0.79569 ,  1.7971  , -0.33392 , -0.14545 ,
       -1.5454  ,  0.0135  ,  0.10684 , -0.30722 , -0.54572 ,  0.38938 ,
        0.24659 , -0.85166 ,  0.54966 ,  0.82679 , -0.68081 , -0.77864 ,
       -0.028242, -0.82872 ])

In [44]:
data['laptop']

array([ 0.59754 , -0.21225 ,  2.1719  ,  0.15673 ,  0.38409 , -0.47869 ,
       -0.060613, -0.9584  ,  0.5184  ,  0.56782 ,  0.062268,  0.13887 ,
       -0.14047 ,  0.082245,  0.39597 ,  0.12775 , -2.03    ,  1.2655  ,
        0.92248 , -0.74247 ,  0.35148 ,  0.064091, -0.30828 ,  0.36743 ,
        0.099275, -1.2918  , -0.22716 ,  0.025201,  0.38823 , -0.76859 ,
        1.3206  ,  0.062628, -0.094857,  0.15232 ,  0.9426  ,  1.1285  ,
        0.10472 ,  0.67856 , -0.19502 , -0.72642 ,  0.9421  ,  0.32248 ,
       -0.25644 ,  0.80243 ,  0.26602 ,  0.022152,  0.80394 , -0.29284 ,
       -0.17015 , -0.394   ])

In [45]:
np.dot(data['grapes'], data['banana'])

13.993197972982001

In [46]:
np.dot(data['banana'], data['laptop'])

2.6648286963269996

In [47]:
np.dot(data['dog'], data['cat'])

19.739068485226

In [48]:
np.dot(data['dog'], data['kite'])

8.8700582186676