In [ ]:
import numpy as np

In [ ]:
a = [1, 2]
b = [5, 7]
print(a)
print(b)

[1, 2]
[5, 7]


In [ ]:
# dot product -> python
a[0]*b[0] + a[1]*b[1]

19

In [ ]:
a = np.array(a)
a

array([1, 2])

In [ ]:
b = np.array(b)
b

array([5, 7])

In [ ]:
np.dot(a, b)

19

In [ ]:
A = np.random.randint(1, 5, (3, 2))
A

array([[2, 3],
       [2, 1],
       [4, 1]])

In [ ]:
B = np.random.randint(1, 5, (2, 4))
B

array([[1, 1, 4, 3],
       [3, 3, 1, 3]])

In [ ]:
np.dot(A, B)

array([[11, 11, 11, 15],
       [ 5,  5,  9,  9],
       [ 7,  7, 17, 15]])

In [ ]:
B

array([[1, 1, 4, 3],
       [3, 3, 1, 3]])

In [ ]:
np.transpose(B)

array([[1, 3],
       [1, 3],
       [4, 1],
       [3, 3]])

In [ ]:
B.T

array([[1, 3],
       [1, 3],
       [4, 1],
       [3, 3]])

In [ ]:
np.matmul(A, B)

array([[11, 11, 11, 15],
       [ 5,  5,  9,  9],
       [ 7,  7, 17, 15]])